version: "3.8"

services:
  portaal_backend:
    image: demo/portaal_backend:${PORTAAL_BACKEND_VERSION}
    restart: always
    environment:
      PORTAAL_BACKEND_PORT: 8000

  portaal_frontend:
    image: demo/portaal_frontend:${PORTAAL_FRONTEND_VERSION}
    restart: always

  nginx:
    image: demo/nginx:${NGINX_VERSION}
    restart: always
    ports:
      - 8080:80

  postgres:
    image: demo/postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
